name: Create release
on:
  push:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    name: Maven build
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Set up Java
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up LibreOffice UNO runtime environment
      run: |
        sudo apt-get update
        sudo apt-get install liblibreoffice-java
    - name: Build and package JAR for Debian
      run: mvn --batch-mode package
    - name: Create assembly for Debian
      run: mvn --batch-mode assembly:single
    - name: Package JAR for Linux
      run: mvn --batch-mode --activate-profiles for-linux package
    - name: Create assembly for Linux
      run: mvn --batch-mode --activate-profiles for-linux assembly:single
    - name: Package JAR for MacOS
      run: mvn --batch-mode --activate-profiles for-macos package
    - name: Create assembly for MacOS
      run: mvn --batch-mode --activate-profiles for-macos assembly:single
    - name: Package JAR for Windows
      run: mvn --batch-mode --activate-profiles for-windows package
    - name: Create assembly for Windows
      run: mvn --batch-mode --activate-profiles for-windows assembly:single
    - name: Upload build artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        compression-level: 0
        path: |
          target/*.tar.gz
          target/*.zip
        retention-days: 1
  release:
    name: Release
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Download build artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        path: target
    - name: Create release with binary build artifacts
      run: |
        gh release create "$TAG_NAME" --draft --title "$TAG_NAME"
        pushd target
        for file in *.tar.gz *.zip ; do
          [ -e "$file" ] || continue
          gh release upload "$TAG_NAME" "$file"
        done
        popd
        gh release edit "$TAG_NAME" --draft=false
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ github.ref_name }}
